<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<ApplicationIcon>Resources\Images\Protocool.ico</ApplicationIcon>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>

		<PublishSingleFile>true</PublishSingleFile>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

		<DebugType>None</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
		<AvaloniaResource Include="Resources\Images\**" />
	</ItemGroup>

	<ItemGroup>
	  <AvaloniaXaml Remove="publish\**" />
	  <Compile Remove="publish\**" />
	  <EmbeddedResource Remove="publish\**" />
	  <None Remove="publish\**" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Handlers\Lua\**\*.lua">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<PackageReference Include="Avalonia" Version="12.1.1" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
		<PackageReference Include="MoonSharp" Version="3.0.0-beta.1" />
		<PackageReference Include="NLog" Version="6.1.4" />
		<PackageReference Include="NLog.Extensions.Logging" Version="6.1.4" />
		<PackageReference Include="Semi.Avalonia" Version="12.1.0" />
		<PackageReference Include="Svg.Controls.Avalonia" Version="12.0.0.13" />
		<PackageReference Include="System.IO.Ports" Version="10.0.10" />
		<PackageReference Include="Xaml.Behaviors.Avalonia" Version="12.0.5" />
		<PackageReference Include="Xaml.Behaviors.Interactions" Version="12.0.5" />
		<PackageReference Include="Xaml.Behaviors.Interactions.Custom" Version="12.0.5" />
		<PackageReference Include="Xaml.Behaviors.Interactivity" Version="12.0.5" />
		<PackageReference Include="YamlDotNet" Version="18.1.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Zenner.Communication.Avalonia\Zenner.Communication.Avalonia.csproj" />
	  <ProjectReference Include="..\Zenner.Communication.Client\Zenner.Communication.Client.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Handlers\Lua\GetVersion.lua">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
