namespace ProtocolSimulator.Models.DataType
{
    public enum MBusDataType : ushort
    {
        // 0xFF in the low byte marks commands that only have an FC and no EFC.

        // Core commands
        Core_GetVersion = 0x06FF,
        Core_GetEnhancedIdentification = 0x0600,
        Core_FlyingTestPrepare = 0x11FF,
        Core_FlyingTestStart = 0x12FF,
        Core_FlyingTestStop = 0x13FF,
        Core_FlyingTestReadVolume = 0x14FF,
        Core_FlyingTestDone = 0x15FF,

        // Common commands
        Common_ResetDevice = 0x80FF,
        Common_SetWriteProtection = 0x81FF,
        Common_OpenWriteProtection = 0x82FF,
        Common_SetGetMode = 0x83FF,
        Common_ReadMemory = 0x84FF,
        Common_WriteMemory = 0x85FF,
        Common_RunBackup = 0x86FF,
        Common_SetGetSystemTime = 0x87FF,
        Common_SetGetKeyDate = 0x88FF,
        Common_SetGetRadioOperation = 0x89FF,
        Common_ClearGetResetCounter = 0x8AFF,
        Common_SetLcdTestState = 0x8BFF,
        Common_SwitchLed = 0x8CFF,
        Common_ActivateDeactivateDisplay = 0x8DFF,
        Common_TimeShift = 0x8EFF,
        Common_ExecuteEvent = 0x8FFF,
        Common_SetRtcCalibration = 0x90FF,
        Common_GetCommunicationScenario = 0x91FF,
        Common_SetCommunicationScenario = 0x92FF,
        Common_GetPrintedSerialNumber = 0x93FF,
        Common_SetPrintedSerialNumber = 0x93FF,
        Common_SetGetLocalInterfaceEncryption = 0x94FF,
        Common_GetSelectableCommunicationScenarios = 0x95FF,
        Common_SetGetDisplayConfiguration = 0x96FF,

        // Radio test commands (FC = 0x2F)
        RadioTest_GetRadioVersion = 0x2F00,
        RadioTest_SetGetTransmitPower = 0x2F05,
        RadioTest_SetGetCenterFrequency = 0x2F06,
        RadioTest_SetGetFrequencyIncrement = 0x2F07,
        RadioTest_SetGetCarrierMode = 0x2F08,
        RadioTest_SetGetFrequencyDeviation = 0x2F09,
        RadioTest_SetGetRxBandwidth = 0x2F0A,
        RadioTest_SetGetTxDataRate = 0x2F0B,
        RadioTest_SetGetRxDataRate = 0x2F0C,
        RadioTest_StopRadioTest = 0x2F20,
        RadioTest_TransmitUnmodulatedCarrier = 0x2F21,
        RadioTest_TransmitModulatedCarrier = 0x2F22,
        RadioTest_SendTestPacket = 0x2F23,
        RadioTest_ReceiveOneR3S3Telegram = 0x2F24,
        RadioTest_ReceiveAndStreamR3S3Telegrams = 0x2F25,
        RadioTest_MonitorRadioToOutput = 0x2F26,
        RadioTest_EchoRadio3TelegramViaRadio = 0x2F27,
        RadioTest_SetGetTxBandwidthLoRa = 0x2F28,
        RadioTest_StartTransmissionCycle = 0x2F29,
        RadioTest_SetNfcField = 0x2F2A,

        // MBus commands (FC = 0x34)
        MBus_SetGetChannelMBusAddress = 0x3401,
        MBus_SetGetChannelIdentification = 0x3402,
        MBus_SetGetChannelObisCode = 0x3403,
        MBus_SetGetChannelConfiguration = 0x3404,
        MBus_SetGetChannelValue = 0x3405,
        MBus_SetGetMBusLoads = 0x3406,
        MBus_ReadChannelLogValue = 0x3410,
        MBus_ReadEventLog = 0x3411,
        MBus_ClearEventLog = 0x3412,
        MBus_ReadSystemLog = 0x3413,
        MBus_ClearSystemLog = 0x3414,
        MBus_ReadChannelSingleLogValue = 0x3415,
        MBus_SetGetRadioList = 0x3416,
        MBus_SetGetTxTimings = 0x3417,
        MBus_SetGetMBusKey = 0x3418,

        // LoRa commands (FC = 0x35)
        LoRa_GetLoRaFcVersion = 0x3500,
        LoRa_GetLoRaWanVersion = 0x3501,
        LoRa_SendJoinRequest = 0x3506,
        LoRa_CheckJoinAccept = 0x3507,
        LoRa_SendUnconfirmedData = 0x3508,
        LoRa_SendConfirmedData = 0x3509,
        LoRa_SetGetNetId = 0x3520,
        LoRa_SetGetAppEui = 0x3521,
        LoRa_SetGetNwkSKey = 0x3522,
        LoRa_SetGetAppSKey = 0x3523,
        LoRa_SetGetOtaaAbp = 0x3524,
        LoRa_SetGetDevEui = 0x3525,
        LoRa_SetGetAppKey = 0x3526,
        LoRa_SetGetDevAddr = 0x3527,
        LoRa_SetGetTransmissionScenario = 0x3528,
        LoRa_SendConfigurationPacket = 0x3529,
        LoRa_SetGetAdaptiveDataRate = 0x352A,
        LoRa_TriggerGetSystemDiagnostic = 0x352B,
        LoRa_SetGetFrequencyPlan = 0x352C,
        LoRa_GetSelectableFrequencyPlans = 0x352D,

        // Special commands (FC = 0x36)
        Special_GetSpecialCommandFcVersion = 0x3600,
        Special_GetCurrentMeasuringMode = 0x3601,
        Special_SetGetMetrologyParameters = 0x3602,
        Special_ActivateDeactivateDisplay = 0x3603,
        Special_SetGetProductFactor = 0x3604,
        Special_SetGetCountingMode = 0x3605,
        Special_SetGetSummertimeCountingSuppression = 0x3606,
        Special_SetGetTransmissionScenario = 0x3607,
        Special_SendConfigurationPacket = 0x3608,
        Special_ClearGetFlowCheckStates = 0x3609,
        Special_ConfigureGetSdRules = 0x360A,
        Special_SendToNfcDevice = 0x360B,
        Special_GetNfcDeviceIdentification = 0x360C,
        Special_SetReligiousDay = 0x360D,
        Special_SetGetSmartFunctions = 0x360E,
        Special_GetValve = 0x360F,
        Special_SetValve = 0x360F,

        // NBIoT commands (FC = 0x37)
        NBIoT_GetModemPartNumber = 0x3700,
        NBIoT_GetFirmwareVersion = 0x3701,
        NBIoT_GetImeiFromModem = 0x3702,
        NBIoT_GetImsiFromModem = 0x3703,
        NBIoT_SetGetProtocol = 0x3704,
        NBIoT_SetGetBand = 0x3705,
        NBIoT_SetGetRemoteIp = 0x3706,
        NBIoT_SetGetRemotePort = 0x3707,
        NBIoT_GetOperator = 0x3708,
        NBIoT_SendConfirmedData = 0x3709,
        NBIoT_SendUnconfirmedData = 0x370A,
        NBIoT_SendTestData = 0x370B,
        NBIoT_SendRadioFullFunctionOnOff = 0x370C,
        NBIoT_GetSimIccid = 0x370D,
        NBIoT_SetGetSecondaryBand = 0x370E,
        NBIoT_SetGetDnsName = 0x370F,
        NBIoT_GetRadioSentState = 0x3710,
        NBIoT_ResetModem = 0x3711,
        NBIoT_SetModemAutoOrManualConnect = 0x3712,
        NBIoT_SetGetModemApn = 0x3713,
        NBIoT_SetGetDnsServerIp = 0x3714,
        NBIoT_PowerOnOff = 0x3720,
        NBIoT_SendCommonCommand = 0x3721,
        NBIoT_GetImeiImsiFirmwareVersionFromRam = 0x3722,
        NBIoT_GetIccidImsiFromRam = 0x3723,
        NBIoT_SetGetDeviceEui = 0x3725,
        NBIoT_SetGetTransmissionScenario = 0x3728,
        NBIoT_SetGetDnsEnableByte = 0x3729,
        NBIoT_SetGetApnEnableByte = 0x3730,
        NBIoT_SendActivedPacket = 0x3731,
        NBIoT_TriggerIntensiveSample = 0x3732,

        // NFC commands (FC = 0x38)
        Nfc_SendNfcCommand = 0x38FF,

        // Metrology test commands (FC = 0x39)
        MetrologyTest_PrepareFlyingVolumeTest = 0x3901,
        MetrologyTest_StartFlyingVolumeTest = 0x3902,
        MetrologyTest_StopFlyingVolumeTest = 0x3903,
        MetrologyTest_GetFlyingVolumeTestResult = 0x3904,
        MetrologyTest_TerminateFlyingVolumeTest = 0x3905,
        MetrologyTest_LcdToFastHighResOn = 0x3906,
        MetrologyTest_LcdToFastHighResOff = 0x3907,
        MetrologyTest_GetMetrologyTableInformation = 0x3908,
        MetrologyTest_GenerateTestPulses = 0x3909,

        // Response function codes
        Response_Ack = 0xFEFF,
        Response_Nack = 0xFFFF,

    }
}
